---
title: "p8105_hw2_wl3013"
author: "Wen Li_wl3013"
date: "2025-09-27"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Question 1
### Step 1: Clean the data in pol-month.csv
```{r}
polmonth_df = 
  read.csv(
    "pols-month.csv",
    na = c("NA",".","")
  ) |> 
  janitor::clean_names() |> 
  separate(mon,into = c("year","month","day",sep = "-")) |>
  mutate(
    month = month.name[as.integer(month)] 
    ) |> 
  mutate(
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )) |> 
  select(-prez_gop, -prez_dem, -day)

```

### Step 2: Clean the data in snp.csv
```{r}
snp_df = 
  read.csv(
    "snp.csv", na = c("NA",".","")
  ) |> 
  janitor::clean_names() |> 
  mutate(date = mdy(date)) |> 
  separate(date,into = c("year","month","day",sep = "-")) |>
  mutate(
    month = month.name[as.integer(month)] 
    ) |> 
  arrange(year, month)
```

### Step 3: Clean the data in unemployment.csv
```{r}
unemp_df = 
  read.csv(
    "unemployment.csv", na = c("NA",".","")
  ) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = -year,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  # Capitalize "month" variable
  mutate(
    month_num = match(str_to_title(month), month.abb),
    month = month.name[month_num]
  ) |> 
  select(-month_num)
```

### Step 4: Merge the datasets
```{r}
# Create a subset for snp, choosing the variables we need for merge
snpsub_df = 
  snp_df |> 
  select(year, month, snp_close = close)

# Change the variable type of "year" from int to chr
unemp_df <- unemp_df |> 
  mutate(year = as.character(year))

merge_df = 
  polmonth_df |> 
  left_join(snpsub_df, by = c("year","month")) |> 
  left_join(unemp_df, by = c("year","month"))

```

